spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      mvc:
        routes:
          - id: service-account
            uri: lb://service-account
            predicates:
              - Path=/account/**
              - Method=GET,POST,PUT,PATCH,DELETE
            filters:
              - RewritePath=/account/?(?<segment>.*), /$\{segment}
          - id: service-order
            uri: lb://service-order
            predicates:
              - Path=/order/**
              - Method=GET,POST,PUT,PATCH,DELETE
            filters:
              - RewritePath=/order/?(?<segment>.*), /$\{segment}
          - id: service-product
            uri: lb://service-product
            predicates:
              - Path=/product/**
              - Method=GET,POST,PUT,PATCH,DELETE
            filters:
              - RewritePath=/product/?(?<segment>.*), /$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE