spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      source:
        url: jdbc:mysql://${ACCOUNT_DB_HOST:localhost}:${ACCOUNT_DB_PORT:3318}/${ACCOUNT_DB_DATABASE:product}
        username: ${ACCOUNT_DB_USER:root}
        password: ${ACCOUNT_DB_PASSWORD:root}
      replica:
        url: jdbc:mysql://${ACCOUNT_DB_REPLICA_HOST:localhost}:${ACCOUNT_DB_REPLICA_PORT:3318}/${ACCOUNT_DB_REPLICA_DATABASE:product}
        username: ${ACCOUNT_DB_REPLICA_USER:root}
        password: ${ACCOUNT_DB_REPLICA_PASSWORD:root}
      maximum-pool-size: ${DB_POOL_SIZE:10}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
      ejb:
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy