spring:
  data:
    redis:
      host: ${REDISHOST}
      username: ${REDISUSER}
      password: ${REDISPASSWORD}
      port: ${REDISPORT}

  datasource:
    url: "jdbc:mysql://${ACCOUNT_DB_HOST:localhost}:${ACCOUNT_DB_PORT:3316}/${ACCOUNT_DB_DATABASE:account}"
    username: ${ACCOUNT_DB_USER:root}
    password: ${ACCOUNT_DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        show_sql: true
      ejb:
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy