spring:
  application:
    name: core-gateway
  config:
    import:
      - "optional:classpath:/config/route.yml"
      - "optional:classpath:/config/database.yml"
      - "optional:classpath:/config/session.yml"
      - "optional:classpath:/config/monitoring.yml"
      - "optional:classpath:/config/message-source.yml"
      - "optional:classpath:/config/auth.yml"
      - "optional:classpath:/config/circuit-breaker.yml"

  profiles:
    active: ${PROFILE:dev}